### ISSUE TITLE
GlobalTracer uses NoopTracer type check to determine if a Tracer has been registered

### ISSUE THREAD

**Issue by MikeGoldsmith** [opentracing/opentracing-csharp#113]
When using the GlobalTracer, I've found that it uses a type check against the configured tracer to determine if a tracer has been registered. 

https://github.com/opentracing/opentracing-csharp/blob/master/src/OpenTracing/Util/GlobalTracer.cs#L62

This causes a problem for us because we wish to set a tracer in our library if one has not already been configured globally. However, if the application intentionally sets a NoopTracer, we would see that as a valid scenario to use our Tracer.

I think an alternative solution would be to use an internal bool of the GlobalTracer to indicate when it has been set instead of relying on that type check.

**Comment by MikeGoldsmith** [comment]
FYI this is common in other implementations too:

Java > https://github.com/opentracing/opentracing-java/blob/master/opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java#L96

**Comment by austinlparker** [comment]
The internal bool idea seems fine to me. Do you want to submit a PR?

**Comment by carlosalberto** [comment]
@MikeGoldsmith Was going to mention the same (and think we could use a bool field for it, too ;) )

**Comment by MikeGoldsmith** [comment]
Yeah, I will create a change for both .NET and Java. 

Note: when checking the other implementations, some didn't utilise a registered method at all to prevent re-registering a tracer. eg Go, Node

**Comment by carlosalberto** [comment]
Python doesn't check it btw, but that was on purpose ;)
