### ISSUE TITLE
Accessing GlobalTracer.IsRegistered is not thread-safe 

### ISSUE THREAD

**Issue by christoph-neumann-schema-de** [opentracing/opentracing-csharp#118]
## Problem - what blocks you from solving the requirement?

In GlobalTracer.cs the writing to s_isRegistered is thread-save via lock(s_lock).
Problem: the accessor is not thread-safe:

public static bool IsRegistered() {
    return s_isRegistered;
}

Consequence:
I would like to initialize the GlobalTracer with something like that:
if (!OpenTracing.Util.GlobalTracer.IsRegistered())
    OpenTracing.Util.GlobalTracer.Register(Tracer);

This would not be thread-safe. It is possible that two threads get IsRegistered:=false, in parallel, and then the Register happends in parallel, which throws an unexpected exception for one of both threads.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Please make reading s_isRegistered as thread-safe as writing it.

        public static bool IsRegistered() {
            lock (s_lock);
                 return s_isRegistered;
        }
		

## Relevance:
The necessary contention is easily reached with just a few (concurrent!) NUnit Test Assemblies. I got it almost at once when I started Tracing-enabled testing.

The proposed solution would not eliminate the problem to 100%. Because Thread 1 and Thread 2 might both be executing IsRegistered and might still be scheduled between both lines if...IsReg and Reg, ending in an Exception on one side due to a race condition. However, adding the lock reduces the problem. After the patch a far higher contention would be needed.

In addition, I have locked my own threads arround the If..IsReg and Reg lines, too, to be 100% sure.
Still, I noticed the delta on your side of the code and wanted to give you this hint.

**Comment by MikeGoldsmith** [comment]
Hi @christoph-neumann-schema-de 

Thanks for the interesting race condition, I'll take a look soon and see how best to move forward.

**Comment by MirzaMerdovic** [comment]
Sorry, if I am a bit off topic here, but why is: [Register method not pure](https://github.com/opentracing/opentracing-csharp/blob/c534179959d4a4160e06456cc70e609f827952e8/src/OpenTracing/Util/GlobalTracer.cs#L92). 
This way we have to first call _IsRegistered()_ to check and then call: _Register()_ and since this is not thread safe it can easily happen that the call fails.

**Comment by MikeGoldsmith** [comment]
@MirzaMerdovic we've added a `RegisterIfAbsent` method in #119 to make this more consistent and predictable.

**Comment by MirzaMerdovic** [comment]
Nice, thanks @MikeGoldsmith!

**Comment by MikeGoldsmith** [comment]
Thread safety has been improved as part of #119. I'm going to close this for now, if you feel more work is needed, we can re-open.

Thanks
