### ISSUE TITLE
Create basictracer-csharp repository

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#12]
@bensigelman @yurishkuro I guess we should also move the BasicTracer to a separate repo, right? Who can create the repository? Would be great if @dawallin and I could get contributor rights there as well :)

**Comment by yurishkuro** [comment]
done and done

**Comment by yurishkuro** [comment]
Visit https://github.com/opentracing/basictracer-csharp/invitations to accept invites

**Comment by cwe1ss** [comment]
thank you!! I guess we'll commit the current version to a non-master branch (I haven't done any real work on it yet) once #10 is merged/rejected because that PR contains a lot of changes in that project.

**Comment by bensigelman** [comment]
@yurishkuro @cwe1ss @dawallin should we create `opentracing-contrib/basictracer-csharp` instead? (Or, per those conventions, `csharp-basictracer`???)

Of course the others would have to move at some point, too, if we went that route. `opentracing-contrib` didn't exist when we started working on basictracers...

**Comment by cwe1ss** [comment]
Depends on how you want to use the basictracer. If it's just a sample/reference implementation that further explains/showcases the OpenTracing API and shouldn't be used directly, I'd prefer keeping it in this organization.

`opentracing-contrib` sounds like a place that contains actual ready-to-use library integrations etc.

But I'm ok with either of them! :)

Reopening this issue until this is decided.

**Comment by yurishkuro** [comment]
I rather like basictracers in the main org, as reference implementations, whereas contrib is more about instrumentation. But no strong feeling.

**Comment by cwe1ss** [comment]
Seems like we can keep the repo in this org for now, so I'll close this again. I'm fine with either so just tell us if you want to move it someday.
