### ISSUE TITLE
Zipkin

### ISSUE THREAD

**Issue by AceHack** [opentracing/opentracing-csharp#121]
How do I configure this library to point to zipkin?

**Comment by austinlparker** [comment]
You would need to use the Zipkin tracer for C#, I believe it's this - https://github.com/openzipkin/zipkin4net

Generally with OpenTracing you don't directly use the interface unless you're writing some shared code that shouldn't have a dependency on a concrete tracer.

**Comment by AceHack** [comment]
Yeah, I don't want a dependency on a concrete tracer because I also want to support yeager, I just want to write the code once, but then how do I point it to zipkin through configuration?  No code changes.

**Comment by austinlparker** [comment]
I think you'd probably be best served by asking in our Gitter chatroom at https://gitter.im/opentracing/public, probably easier to work through this there than in github issues. :)
