### ISSUE TITLE
Manully set timespans and durations

### ISSUE THREAD

**Issue by AceHack** [opentracing/opentracing-csharp#122]
How do I manually set timespans and durations?

**Comment by cwe1ss** [comment]
There are overloads that allow you to pass in timestamps - e.g. `ISpanBuilder.WithStartTimestamp(DateTimeOffset timestamp)` or `ISpan.Finish(DateTimeOffset finishTimestamp)`.

I'm closing this as it's an old issue (sorry for not replying). Please comment or create a new issue if this does not answer your question.
