### ISSUE TITLE
Zipkin and Jaeger

### ISSUE THREAD

**Issue by AceHack** [opentracing/opentracing-csharp#123]
How do I configure this library to point to zipkin or jaeger?

**Comment by cwe1ss** [comment]
Hello, this library is just the common set of interfaces and types that is being used by tracers and instrumentation code. In .NET Core & .NET 5 apps you can use e.g. [OpenTracing.Contrib.NetCore](https://www.nuget.org/packages/OpenTracing.Contrib.NetCore) which automatically instruments the apps and creates the spans that can then be used by the tracer's .NET libraries - e.g. [Jaeger](https://www.nuget.org/packages/Jaeger). 

See https://github.com/opentracing-contrib/csharp-netcore/tree/master/samples for some samples that use both described libraries.

Please comment or create a new issue if this does not answer your question.
