### ISSUE TITLE
QUE: is Tags.SamplingPriority being used 

### ISSUE THREAD

**Issue by lghinet** [opentracing/opentracing-csharp#124]
hello,
 is Tags.SamplingPriority on operation being used ?

**Comment by cwe1ss** [comment]
Hello. This project just defines the set of interfaces and types that are being used by actual tracers (e.g. Jaeger) and instrumentation libraries (e.g. OpenTracing.Contrib.NetCore). You therefore have to check their docs/repos to see if a given tag is used. 

Please comment or open a new issue if this does not answer your question.
