### ISSUE TITLE
How I can kown which http request execute Entity Framework Core Command

### ISSUE THREAD

**Issue by 564064202** [opentracing/opentracing-csharp#125]
How I can kown which http request execute Entity Framework Core Command

**Comment by cwe1ss** [comment]
Sorry for the late response - it probably won't help you but maybe it helps someone else. This library is a set of interfaces that need to be implemented by a tracer (e.g. Jaeger) and by some instrumentation library.

If you already get spans for EF Core, then you're already using a OpenTracing-compatible instrumentation library. You need to check their docs/repos to see how they instrument the calling ASP.NET Core requests. If you're using `OpenTracing.Contrib.NetCore` your EF Core spans should automatically show up underneath your ASP.NET Core request spans.

Please comment with further details or open a new issue if this does not answer your question.
