### ISSUE TITLE
Data in CallContext/AsyncLocal is not persisted when ActiveSpan is started from Application_BeginRequest and a thread switch occurs

### ISSUE THREAD

**Issue by stanisls** [opentracing/opentracing-csharp#127]
I have been debugging a peculiar issue where ActiveSpan would occasionally disappear (would become null) in the controller code, after it was set in `Application_BeginRequest` in Global.asax.cs. In theses cases ActiveSpan would also be null in `Application_EndRequest`.

The WebAPI application targets .Net 4.6.1, but it seems that net45 build from NuGet is used. After digging down into the OpenTracing code, I became interested in the use of `CallContext` here https://github.com/opentracing/opentracing-csharp/blob/master/src/OpenTracing/Util/AsyncLocalScopeManager.cs

Getting CallContext data from the Immediate window at strategically placed breakpoints confirmed that it would at times return null. As this was not consistent (at times `CallContext` would persist into the controller method call), I started suspecting thread switching in the .Net framework coupled with timing and load variations.

A search confirmed my suspicion in the form of this article from 2005:
https://piers7.blogspot.com/2005/11/threadstatic-callcontext-and_02.html

> 
> The second thread has had the HttpContext migrated from the first, but not the CallContext or the ThreadStatic's (NB: since HttpContext is itself stored in CallContext, this means ASP.Net is explicitly migrating the HttpContext across). Let's just spell this out again:
> 
>     The thread switch occurs after the IHttpHandler has been created
>     After the page's field initializers and constructor run
>     After any BeginRequest, AuthenticateRequest, AquireSessionState type events that your Global.ASA / IHttpModules are using.
>     Only the HttpContext migrates to the new thread

This behaviour is exactly what I experience when I start an ActiveSpan in either `Application_BeginRequest` of Global.asax.cs or in `OnActionExecuting` of a dedicated ActionFilter.

But it is still worth noting that the pattern of starting a span at the beginning of a request does not consistently work as long as opentracing-csharp implementation uses CallContext for persistence of the ActiveSpan in .Net Framework 4.5

**Comment by stanisls** [comment]
OpenTracing NNuGet package was installed with the following HintPath:
`<HintPath>..\packages\OpenTracing.0.12.0\lib\net45\OpenTracing.dll</HintPath>`
even though the projects in my solution target 4.6.1

I've update this HintPath in all projects to 
`<HintPath>..\packages\OpenTracing.0.12.0\lib\netstandard2.0\OpenTracing.dll</HintPath>`
and running the application I see that the ScopeManager is now using AsyncLocal.
This fixed the persistence problem is an Active span is started from `Application_BeginRequest`. However, if it is started from an ActionFilter, then the reference to it is lost when the execution enters the controller method.

**Comment by stanisls** [comment]
I solved this by creating a scope manager around HttpContext:

HttpContextScope.cs:
´´´c#
using OpenTracing;

namespace Services.OpenTracing
{
    public class HttpContextScope : IScope
    {
        private readonly HttpContextScopeManager _scopeManager;
        private readonly bool _finishOnDispose;
        private readonly IScope _scopeToRestore;

        public HttpContextScope(HttpContextScopeManager scopeManager, ISpan wrappedSpan, bool finishOnDispose)
        {
            _scopeManager = scopeManager;
            Span = wrappedSpan;
            _finishOnDispose = finishOnDispose;

            _scopeToRestore = scopeManager.Active;
            scopeManager.Active = this;
        }

        public ISpan Span { get; }

        public void Dispose()
        {
            if (_scopeManager.Active != this)
            {
                // This shouldn't happen if users call methods in the expected order. Bail out.
                return;
            }

            if (_finishOnDispose)
            {
                Span.Finish();
            }

            _scopeManager.Active = _scopeToRestore;
        }
    }
}
´´´

HttpContextScopeManager.cs:
´´´c#
using System;
using System.Web;
using OpenTracing;

namespace Services.OpenTracing
{
    public class HttpContextScopeManager : IScopeManager
    {
        private readonly string _httpcontextKey = nameof(HttpContextScope) + "__" + Guid.NewGuid().ToString("D");

        public IScope Activate(ISpan span, bool finishSpanOnDispose)
        {
            return new HttpContextScope(this, span, finishSpanOnDispose);
        }

        public IScope Active
        {
            get
            {
                if (HttpContext.Current.Items.Contains(_httpcontextKey))
                {
                    return HttpContext.Current.Items[_httpcontextKey] as IScope;
                }

                return null;
            }

            set
            {
                if (HttpContext.Current.Items.Contains(_httpcontextKey))
                {
                    HttpContext.Current.Items[_httpcontextKey] = value;
                }
                else
                {
                    HttpContext.Current.Items.Add(_httpcontextKey, value);
                }
            }
        }
    }
}
´´´
This can probably be taken into the project under ´OpenTracing.Utils´ at the cost of an added dependency  on ´System.Web´

**Comment by davidfowl** [comment]
Seems reasonable to do this for .NET 4.x applications running on System.web

**Comment by cwe1ss** [comment]
Sounds like the same problem as described in #137 - we're missing a `net46` target for the library.

I'll close this as the other issue has some more details on the problem. thank you for reporting this. 

Feel free to comment or create a new issue if I misunderstood.
