### ISSUE TITLE
How to log errors when the the application can't reach the Jaerger server?

### ISSUE THREAD

**Issue by ivanpaulovich** [opentracing/opentracing-csharp#134]
Hi!

First of all, Jaeger is great, useful and is saving lifes :)

I was able to run seamlessly my application when using the All-in-one jaeger:

```sh
docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.14
```

The application was registered, metrics were sent and I could query the spans. Later on I decided to use jaergertracing within k8s with the following command:

```sh
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml

kubectl port-forward jaeger-bb7b55f49-8mzg7 5775 &
kubectl port-forward jaeger-bb7b55f49-8mzg7 6831 &
kubectl port-forward jaeger-bb7b55f49-8mzg7 6832 &
kubectl port-forward jaeger-bb7b55f49-8mzg7 5778 &
kubectl port-forward jaeger-bb7b55f49-8mzg7 16686 &
kubectl port-forward jaeger-bb7b55f49-8mzg7 14268 &
kubectl port-forward jaeger-bb7b55f49-8mzg7 9411 &
```

I was able to navigate to the Jager page, the server seems to be working fine. 
Unfortunately the application could not register itself in the Jaeger UI and no errors are displayed. It is completely silent.

What happens if the application can't connect to Jaeger?
How can I ensure that the c-sharp client is able to reach the Jaeger?

**Comment by cwe1ss** [comment]
This OpenTracing-csharp library is just a set of interfaces and the implementation is up to the tracer (in your case, Jaeger). This means that it's the tracer that has to provide the proper logging capabilities. Please have a look at their docs/repos to see which logging capabilities they provide.
