### ISSUE TITLE
Remove the "SpanReference" type

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#16]
Right now, Span references are represented by a separate type that is a String/SpanContext tuple. I think the main reason for this was the `StartSpanOptions` class which had a list of references. It wouldn't have looked good to use `List<KeyValuePair<string, ISpanContext>>` there.

Now that we exclusively use the builder pattern, it's not really necessary to keep this separate type because the builder has separate methods anyway (e.g. `ISpanBuilder.AsChildOf(ISpanContext parent)`).

Proposed API diff:
```diff
// Files: 
- SpanReference.cs

// ISpanBuilder:
-ISpanBuilder AddReference(SpanReference reference);
+ISpanBuilder AddReference(string referenceType, ISpanContext referencedContext)
```

This way, the implementation would be equal to the Java version.

Do you see any issues with this? If not, I'll probably change this on Thursday/Friday.

**Comment by bensigelman** [comment]
I think that makes a lot of sense and would mirror similar things that happened on the Java side.

**Comment by dawallin** [comment]
Sound good. One type less to maintain.

**Comment by cwe1ss** [comment]
enough feedback! :) I made the changes. should there be any other concerns, please just add a comment here or open a new issue.
