### ISSUE TITLE
Get access to https://www.nuget.org/profiles/OpenTracing

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#19]
There is already a 0.8.2 package of this library and of the BasicTracer on the .NET package manager nuget.org: https://www.nuget.org/profiles/OpenTracing

* Who has access to this account? ( @bensigelman @dawallin @yurishkuro )
* Is it at least two people?
* Could I get the credentials as well? For publishing, we only need an API key, but it would be useful to have the credentials as well in case we have to unlist packages etc.
  * Of course, I'm also ok, if you don't want to give the account to me!

As soon as we have access, I think we should unlist `OpenTracing.BasicTracer` - IMO this is not meant as a library that someone should take a dependency on. It's just a reference implementation and we haven't done much work on it yet.

**Comment by bensigelman** [comment]
@cwe1ss I agree re `BasicTracer`... maybe that should change once the primary API is demonstrably stable and in use in production, but not before.

**Comment by cwe1ss** [comment]
fyi: I've just seen that it would also be possible to add co-owners to packages. But AFAIU this would also list every owner on the package detail page. So I guess using a shared account with the nice "opentracing" name is better.

Source: https://docs.nuget.org/create/managing-package-owners

**Comment by dawallin** [comment]
@cwe1ss I got the nuget account right now. Of course we should share its credentials.

Looking around how other open source projects do I see different patterns for author and owner. Authors are in most cases just the organisation. The organisation is then also the owner, sometimes with the core contributors as co-owners.

For the BasicTracer I think it's fine to have it listed as long as the description clearly states that it is moving and will have backwards-incompatible changes (which I think it already does). Maybe we could add something that it is not a "real" tracer, and more thought of as a simple reference tracer.

**Comment by cwe1ss** [comment]
I now have access to the account - thanks @dawallin !!

What are use-cases where we want people to actually use BasicTracer? Isn't it just a demo for actual trace implementations?

If we release it, we need to follow backwards-compatibility rules and can't use it as a "state of the art" reference implementation that might change at every time.

**Comment by dawallin** [comment]
I agree that we don't want anyone to start take dependencies against BasicTracer. But we like others to start play around with it. If it is not on nuget, you need to download and build yourself, which will raise the barrier to get started. For me, BasicTracer does not need to follow release numbers of OpenTracing and as long as it stays below version 1.0, and we state in the description that it is just a reference tracer which is not guaranteed to be backwards-compatible, I thing that is enough and at the same time make Open Tracing more visible on nuget.

**Comment by cwe1ss** [comment]
> If it is not on nuget, you need to download and build yourself, which will raise the barrier to get started.

The current basic tracer doesn't provide any output so if I understand correctly, there's no value in using it as a binary dependency - its only current value is the source code and unit tests that show the principles.

I'd like to release a version of the main OpenTracing library soon (to finally start using it somewhere :smile:) and since we haven't looked at the BasicTracer code in much detail, I would prefer not releasing it - not even as a pre-release. However if we don't unlist the existing BasicTracer-package on nuget, it would no longer work against the current OpenTracing version. 

@dawallin For this reason, would you be ok with unlisting it until we've figured out who and how we'll proceed with the basictracer implementation?

**Comment by dawallin** [comment]
Yes @cwe1ss , I see your point. I unlisted all versions of BasicTracer on nuget.

**Comment by dawallin** [comment]
Related to #20.

**Comment by cwe1ss** [comment]
Great, thank you!
