### ISSUE TITLE
Review package description for the official .NET package manager nuget.org

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#20]
Before we publish a new version of the package to nuget.org, we should get some green lights regarding the package description that will be shown there.

This is the current version: (from [project.json](https://github.com/opentracing/opentracing-csharp/blob/master/src/OpenTracing/project.json#L3))

``` json
{
  "summary": "A .NET implementation of the OpenTracing API.",
  "description": "This library is a .NET implementation of the OpenTracing API. To fully understand this platform API, it's helpful to be familiar with the OpenTracing project and terminology more generally.\r\n\r\nFor the time being, \"mild\" backwards-incompatible changes may be made without changing the major version number. As OpenTracing and opentracing-csharp mature, backwards compatibility will become more of a priority.",
  "authors": [ "The OpenTracing Authors" ],
  "projectUrl": "https://github.com/opentracing/opentracing-csharp",
  "iconUrl": "https://avatars0.githubusercontent.com/u/15482765",
  "licenseUrl": "https://raw.githubusercontent.com/opentracing/opentracing-csharp/master/LICENSE",
  "tags": [ "opentracing", "distributed-tracing", "tracing", "logging" ],
  "repository": {
    "type": "git",
    "url": "git://github.com/opentracing/opentracing-csharp"
  }
}
```

@bensigelman @dawallin @yurishkuro - It would be great if you could give your feedback and CC other people who should be involved in this.

**Comment by bensigelman** [comment]
@cwe1ss I think that generally looks good. Do you need/want an email address? I think we have a barely-used one for OT committers which would be appropriate here. (For credential recovery, etc)

**Comment by dawallin** [comment]
The email address does not show up here but it is instead added to the nuget owner account. Right now it is my email, maybe we should change it to a OT owned one.

**Comment by cwe1ss** [comment]
Maybe it would yet be best to have co-owners on the packages?! We could change the email address of the current "OpenTracing" account to an official address and have you and me as co-owners with our own email address. This way, we don't have to share passwords and whoever owns the official OT email address would always have a way to get access to the packages should you or I be unavailable.

**Comment by dawallin** [comment]
I think this sounds like a good idea. I added myself as an co-owner. I didn't know your name @cwe1ss so you have to add it yourself. @bensigelman, do you have an open tracing email we use for the OpenTracing nuget user? Me and @cwe1ss will have separate access so it is only that the OpenTracing organization can use it as a backup.

**Comment by cwe1ss** [comment]
I added myself as well. We'll close this issue once we have changed the email address of the OpenTracing account.

**Comment by bensigelman** [comment]
@cwe1ss @dawallin `info@opentracing.io` is an alias I have access to for "emergencies", etc. Good idea, thanks!

**Comment by dawallin** [comment]
@bensigelman I added the email above to the gravatar account (needed for nuget). You should have received a verification email. Once this is done I can change the email on the nuget owner.

**Comment by dawallin** [comment]
@cwe1ss I added you as co-owner of the BasicTracer nuget.

**Comment by bensigelman** [comment]
@dawallin I tried to do the gravatar thing and got:

![image](https://cloud.githubusercontent.com/assets/2251553/19504618/894072d0-9570-11e6-8c0b-d29b2a326e7c.png)

Grr, how annoying! Maybe try to find me on Gitter when we're both online and we can get the transaction done quickly.

**Comment by cwe1ss** [comment]
@dawallin @bhs has this ever been resolved?

**Comment by bhs** [comment]
@cwe1ss I am as ignorant about the .NET/C# ecosystem as I was a year ago... that said, I do not see any `nuget` stuff in my inbox from around the time of this issue. If I can help with anything, please let me know.

**Comment by dawallin** [comment]
We have now transferred the ownership of the OpenTracing nuget account. This issue can be closed.

**Comment by cwe1ss** [comment]
awesome, thank you.
