### ISSUE TITLE
Integrate with Travis build server

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#21]
I have seen that other projects use travis-ci for build integration and I would like to set this up for this repo as well. 

* Who can create the build project in the opentracing account and link it with this repository?
* @dawallin do you have experience with travis config files for .NET? (It should be using the new `dotnet cli`). If not, I'll try to create a config file - I've only worked with AppVeyor so far so I'll probably need a few shots/commits to get it right. 

My plan is to have a script that runs build, tests and creates the nuget packages as artifacts. If travis also has some way to do deployments to nuget, that would be even better.

**Comment by dawallin** [comment]
I have no experience of Travis. I integrated to AppVeyor before but they had problems with the new NUnit test runner so I never got a green light from the tests. Now when we use XUnit it maybe works better. I didn't had time to get all the nuget packaging and deploying configured so there is not much at AppVeyor today.

I have no preferences, but to me it looks like AppVeyor is more Windows centric and Travis is more Linux centric . If you have the time to look into Travis I would say go.

**Comment by cwe1ss** [comment]
The repo now contains a .travis.yml file that should work (at least it did in my branch :smile:). 

Could someone please activate this repository in the opentracing travis account? @bensigelman @dawallin @yurishkuro

**Comment by bensigelman** [comment]
@cwe1ss done!

![image](https://cloud.githubusercontent.com/assets/2251553/18528938/e8859b78-7a7f-11e6-9b83-822061915e1f.png)

**Comment by bensigelman** [comment]
oh, and

![image](https://cloud.githubusercontent.com/assets/2251553/18528948/f5cdd318-7a7f-11e6-9a65-20a5dac1a394.png)

**Comment by cwe1ss** [comment]
@bensigelman thank you!!

working build:
![travis-build](https://cloud.githubusercontent.com/assets/4581460/18529555/d87cc780-7acd-11e6-8038-cf81640cc376.PNG)

and there's now also the badge on the repo:
![travis-badge](https://cloud.githubusercontent.com/assets/4581460/18529589/fde128a4-7acd-11e6-8754-b08da0e3f6af.PNG)
