### ISSUE TITLE
Is MIT license + no license headers correct?

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#23]
@bensigelman @dawallin @yurishkuro 

Just to be safe, is using MIT with no license headers ok for you?

Other languages:
* Java: Apache-2.0, license headers
* JavaScript: MIT, no license headers
* Go: MIT, no license headers
* Python: MIT, license headers
* Objective-C: MIT, no license headers
* C++: MIT, no license headers

**Comment by bensigelman** [comment]
@cwe1ss thanks for asking; the OT policy to date has been to do whatever relatively permissive license is idiomatic for common OSS software in the given platform. I.e., do whatever is common in the C# universe.

I don't think license headers are legally necessary so I'm fine skipping them. Though again this is a per-platform thing and there are lots of Java projects that include them.

**Comment by cwe1ss** [comment]
ok - I guess MIT is perfectly fine then. The new x-plat .NET and many other libraries are MIT as well!
