### ISSUE TITLE
Consider changing the builds?

### ISSUE THREAD

**Issue by TerribleDev** [opentracing/opentracing-csharp#38]
Right now the builds are done in powershell with psake, which I cannot run on my ubuntu laptop. Do you think it would make more sense to switch the task system to something node, ruby, or even just c#.

I wrote a [gulp plugin](https://www.npmjs.com/package/gulp-dotnet-cli) for the new cli, mostly because my team codes and runs dotnet on *nix.

**Comment by cwe1ss** [comment]
See #39. 

thanks to .NET Core the build process is pretty simple and I therefore don't want to bring in a completely new stack with node.js, npm, gulp etc.

The ASP.NET Core team uses Cake (C# make), however I don't like the fact that it's an abstraction over very simple command line statements. 

So for now, the simplest solution is a simple bash script as in the referenced PR. We can switch to a more sophisticated solution once we need it.
