### ISSUE TITLE
Question, Use enum for reference instead of string?

### ISSUE THREAD

**Issue by gideonkorir** [opentracing/opentracing-csharp#40]
1st off thanks for the great work. Going through the code and wondering if we should have an ```enum``` for for the reference instead of a ```string```. Something along the lines of:

```c#
public enum SpanReference{
   ChildOf = 1,
   FollowsFrom = 2
}
```

Why?

1. This feels more discoverable to me especially on the ```ISpanBuilder```
2. My initial thoughts are you'll have to update the library anyways since the underlying implementations (e.g. zipkin) would need to be modified to interpret the new reference type

**Comment by cwe1ss** [comment]
With an `enum` users would no longer be able to use their own reference types.

@bhs @yurishkuro What's your opinion on this? The [specification](https://github.com/opentracing/specification/blob/master/specification.md#references-between-spans) only says that OT might support other types in the future (which would just be another enum member) but it doesn't say anything about whether or not users could/should use their own types.

**Comment by yurishkuro** [comment]
My preference is to leave an open API where more references can be added by the user _before_ they make it to the official API.

**Comment by gideonkorir** [comment]
Closing that issue based on @yurishkuro feedback; thanks for the feedback
