### ISSUE TITLE
Replace DateTime usage with DateTimeOffset

### ISSUE THREAD

**Issue by hotchkj** [opentracing/opentracing-csharp#42]
Really pleased to see OpenTracing start up for .NET! Based on what they're used for, I wanted to suggest that the various interfaces be updated to use `DateTimeOffset` for logging etc. This would be really helpful for implementers (for example the company I work for is implementing a tracer for use internally).

This would match [MSDN docs](https://blogs.msdn.microsoft.com/davidrickard/2012/04/06/datetime-and-datetimeoffset-in-net-good-practices-and-common-pitfalls/) on the subject. There's also a great [StackOverflow](https://stackoverflow.com/questions/4331189/datetime-vs-datetimeoffset) topic providing an analogy for why `DateTimeOffset` should be used for this sort of tracing.

Top of the list is that `DateTimeOffset` serialises unambiguously which I believe will be a big help in implementing propagators correctly.

Example of Serilog logging framework using this for timestamps: https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEvent.cs#L52

**Comment by cwe1ss** [comment]
See https://github.com/opentracing/opentracing-csharp/issues/4 for the reasons why we chose `DateTime`.

Please post your scenario if you disagree.

**Comment by hotchkj** [comment]
The intent of the interface `ISpan Log(DateTime timestamp, string eventName);` appears to be to log an occurrence at a specific point in time. Providing a `DateTimeOffset` is always correct & unambiguous, and in codebases that are following Microsoft guidance, all of the existing code would already be using `DateTimeOffset` for tracking timestamps (as I indicated, major .NET logging frameworks already do).

The choice of `DateTime` in the interface means we must convert from `DateTimeOffset` everywhere to `DateTime` which returns, as per docs, `The value of the DateTime.Kind property of the returned DateTime object is DateTimeKind.Unspecified.` which gives exactly the problem you outlined in #4 - every time we convert to OpenTracing format, we have to be aware of all of the pitfalls that `DateTimeOffset` is designed to avoid. This makes the library harder to work with, not easier.

I can provide more arguments, but I'd stand by the original linked article - Microsoft have made it very clear that modern .NET code should prefer `DateTimeOffset` wherever possible.

**Comment by cwe1ss** [comment]
DateTimeOffset is only useful when you want to store the offset (e.g. for local user dates). This (IMO) does not make much sense for server scenarios where you always need UTC.

Also, all other opentracing languages do not support offsets either. This probably also means that most tracers do not support time zones.

DateTimeOffset also has some quite critical drawbacks e.g. it assumes DateTimeKind.Local if a DateTime with DateTimeKind.Unspecified is passed)

The MSDN guidelines say that DateTime should be used if only UTC is needed.

Could you please give me an actual use case for passing a non-UTC timestamp and also how this should be handled by a tracing system?

Sorry for arguing, I just want to make sure, we do the right thing here.

PS: Microsoft recently added an Opentracing-like component (`Activity` in System.Diagnostics.DiagnosticSource) where they also use DateTime.

**Comment by hotchkj** [comment]
No problem with debate! I too want to be sure things are right :) Interfaces are important.

I am in no way proposing that tracers pass down offsets; apologies if I conveyed that. Far from it; I would expect the bulk of tracers to always convert to UTC and/or even epoch time. The most important criteria from my perspective is that what I pass in as a client is 100% correctly reflected as a time entry by the tracer. If that is corruptable in any way, that weakens faith in the entire tracing stack.

I believe you're focusing on the other end of the problem (and nothing wrong with that!). My concern is callers doing the right thing and not accidentally using the interface incorrectly. The current interface requires the caller to have all the knowledge that we are discussing, and that does not appear to be as generally available as one might like.

I would argue `DateTimeOffset` is one of few correct representations for a timestamp because if the timestamp happens to contain an offset, code still has all available knowledge in fetching the UTC representation of that timestamp. `DateTimeOffset.Now` still gives you a correct timestamp that is the same moment in time as `DateTimeOffset.UtcNow`; just it so happens it formats to a different string if you ask for e.g. ISO8601. `DateTime` equivalents do not do this.

It is correct that _if only_ UTC is used, DateTime is acceptable, but you cannot enforce that contract in an .NET interface. One cannot use a `DateTime` as a timestamp _except_ as explicitly UTC (because all the other `Kind` values are meaningless for timestamping - you can never be 100% certain that Local is actually referring to the current machine's local time zone), and that is a more fragile contract for storage & handling. If I pass in a `DateTime` of kind `Unspecified`, the tracer has absolutely no idea what the correct representation is, nor how to correctly convert to a UTC propagation format.

You are in essence requiring that every implementation throw an exception if the DateTime provided is not `Kind.Utc` (or else you are into undefined behaviour or the tracer having to guess, both of which are undesirable). Thus my argument is based in the type being too generic/fuzzy and it's feasible to pass in well-intended but incorrect data. It's harder to 'fall into the pit of success'.

I'm arguing for an interface where the users are least likely to shoot themselves in the foot. I am less invested in the specific of `DateTimeOffset` except that it happens to be a convenient .NET representation of absolute moment in time that is not arguable. I would be just as comfortable with a `long` describing epoch microseconds in UTC, because that too is inarguably an absolute moment in time. It's easy to write a wrapper/extension method that converts `DateTimeOffset` to such a long. It's impossible to write one generically & fully correctly for all kinds of `DateTime`.

I recognise the concerns around taking a `DateTime` of varying `Kind`, wanting to pass it into the span, and having the `DateTimeOffset` conversion do something just as irritating. I would still believe that either a `long` that is well defined or `DateTimeOffset` guides the caller more towards the right thing. Someone debugging their span calls would at least be able to see that the `DateTime`->`DateTimeOffset` conversion did something they were not intending, correct it in their calling code, and tracing then works correctly.

A compromise would be that the interface itself uses `long`, and either the library itself or contributors can add extension methods that do the conversion from as many different types as one cares to add, as long as it's always clear how to get UTC.

Hope that explains more thoroughly, with apologies for the lengthy reply :)

**Comment by cwe1ss** [comment]
I fully agree that `DateTimeOffset` is a "better/more complete" representation of a point in time (internally, it's a DateTime and an int16-offset) and that there are many good use cases for it. However, I'm still missing the *actual scenario* for a logging/tracing tool.

The logging/tracing tool has to show all events from all involved systems in a ordered way. This can only be achieved if all timestamps use the same time zone. This means that either *none (=UTC) or all* timestamps have to include time zone info. As other languages don't support time zone info, I doubt that tracers can/want to deal with it.

In other words, there's not really a functional advantage of having the separate offset that using `DateTimeOffset` provides.

So the only reason to use `DateTimeOffset` would be that its usage is "easier/more obvious" for developers.

However, I don't think that this is the case. No matter which type is used, developers always have to know their behavior:
* With `DateTime` they would have to know that they need to specify Kind.Utc
* With `DateTimeOffset` they have to know that they may not pass a DateTime with Kind.Unspecified either to the DateTimeOffset-constructor or to the methods directly - as that will implicitly [assume Kind.Local](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/DateTimeOffset.cs#L73) and therefore "change" the date (unless people really expected this behavior which I doubt). 
* Also, if we would use ticks with a `long`, people would still have to know how to get this value.

So I don't think there's a perfect solution for this and the main question is, what do most people want/expect and is moving to `DateTimeOffset` worth the (certainly small) performance impact.

CoreFx's new Activity type [requires UTC](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L233) by giving the parameters an "Utc" suffix and by raising an error if an invalid kind is passed. 

Unfortunately, we can't enforce the `Kind` by throwing an exception in an interface. We could however add the "Utc" suffix to the parameters - however this would just be a conventional hint.

**Comment by hotchkj** [comment]
Why _would_ you pass a `DateTime` to a `DateTimeOffset`? Why wouldn't you start with `DateTimeOffset` and just have correct time throughout your codebase to start with? That's the opposing viewpoint I suppose I'm coming from.

As I said previously, I am not stating that internal timestamps of OpenTracing need to support offsets. I have not stated this. The internals of how a tracer handles a timestamp is completely irrelevant to the conversation. What matters is a useful usable interface that allows specification of the timestamp in a correctly handled fashion. If you offer `ISpan Log(DateTime timestamp, string eventName)` you are expecting a caller to _provide_ a time.

The concrete example is that I can pass the result of `DateTimeOffset.Now` to a modern logging system like Serilog and the timestamp will be 100% correct, and whatever conversions it goes through internally gets me a UTC timestamp in whatever serialisation is desired that reflects that. I don't need to care as a caller; it does the right thing; it has enough information to do the right thing. That is the significant functional advantage over a logging system where we have to tell our developers 'do not use this directly, use this wrapper that actually works correctly'.

For me, sticking Utc on the end and then requiring all implementers to remember to implement a check is setting up for failure at some point. A different matter if you were implementing a concrete type, of course, but this code is not. Why use conventional hints when you have types that do it for you? Why not provide extension methods that do the right thing?

Ultimately you can organise the library as you wish, and if necessary we can fork or wrap it, and indeed other implementations can surface more effective methods. It's fairly easy for us internally to just state 'don't use OpenTracing interfaces directly' and add extensions that perform correctly. The intent of this issue was to reduce the pain & confusion of downstream implementors since we are hitting exactly that.

**Comment by cwe1ss** [comment]
My mind isn't made up. :smile: It's a very important interface so this should just be well-discussed.

> If you offer ISpan Log(DateTime timestamp, string eventName) you are expecting a caller to provide a time.

There's overloads without the timestamp parameter for each method and people are expected to call those most of the time. The overloads with a timestamp mostly exist to support scenarios where a span is created from historical data (e.g. from a log file). So there's not really a reason to call one of these overloads with DateTime.UtcNow, DateTimeOffset.Now etc.

> A different matter if you were implementing a concrete type, of course, but this code is not. Why use conventional hints when you have types that do it for you? Why not provide extension methods that do the right thing?

I agree to this argument! 

I also think that tracers could still work with `DateTime` internally to get the performance benefit. 

Given this and the fact that `DateTimeOffset` has more advantages than disadvantages, I'm ok with changing this! 

Does anyone else have an opinion about this? (e.g. @dawallin )

**Comment by cwe1ss** [comment]
fixed with #43

**Comment by hotchkj** [comment]
I got moved on projects and managed to completely forget about this issue in a haze of urgent internal issues, so I just wanted to pop back and say thank you for this! Really appreciate the dialogue and the willingness to listen.
