### ISSUE TITLE
BasicTracer package missing

### ISSUE THREAD

**Issue by ndrwrbgs** [opentracing/opentracing-csharp#48]
The README.md mentions the BasicTracer included in this package, but there is no such package. Furthermore, https://github.com/opentracing/basictracer-csharp is an empty repository.

Is there another place hosting this sample code, or is this something that we should add? I believe @cwe1ss has some code on his repository that was looking for a home - perhaps this library should reference the basictracer-csharp one, and the code be hosted there?

**Comment by gideonkorir** [comment]
@ndrwrbgs not sure if I should add this here, but I have a zipkin v2 tracer at [Jasiri](https://github.com/gideonkorir/Jasiri)

**Comment by cwe1ss** [comment]
There‘s a branch with some code in that repository but it’s just a prototype.

**Comment by cwe1ss** [comment]
"Basic Tracer" is a topic that has been mentioned a few times on gitter and in the cross-language meeting. It exists in some languages and it doesn't exist in some others (e.g. Java).

I'm moving it to "Backlog" as I'd rather invest some time in getting a proper tracer library done ASAP. 

Feel free to comment here if you want to work on this.

**Comment by kfrajtak** [comment]
Just out of curiosity, why is the default implementation of span and/or span builder missing?

**Comment by ndrwrbgs** [comment]
@cwe1ss would you be okay with me contributing an implementation?
Any 'basic' implementation I would make would likely be close the interfaces (given I translated those from java 😜) but would provide a plug-in-able way to configure the SpanId's to be able to support https://github.com/Microsoft/CorrelationVector as a provider of SpanIds (but without taking a dependency on that package).

Does this sound okay or worthless or duplicate work form something existing, etc?

The main thing I want is something that can do traces in an easy way, provide `context` propagation, but not keep them all in memory like `MockTracer` does.

**Comment by cwe1ss** [comment]
@ndrwrbgs sure, but I wonder if it's worth it, given that OpenTelemetry is making (slow) progress?! I haven't been involved in any tracing relevant things over the last year though (I'm renovating a house), so I don't really know anything about the OpenTelemetry timeline.

**Comment by ndrwrbgs** [comment]
I feel I'm doing a disservice to the community - given the current situation is "the old thing is deprecated but the new thing isn't ready yet" - but I'm going to close this to shorten my backlog and be more realistic. Might open a new one later if it comes to it :-)
