### ISSUE TITLE
Unlist OpenTracing.Signed from nuget once we have a new release

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#90]
As discussed in #78, the unofficial [OpenTracing.Signed](https://www.nuget.org/packages/OpenTracing.Signed/) package should be unlisted after we've released v0.12.0.

**Comment by MikeGoldsmith** [comment]
Thanks @cwe1ss

**Comment by MikeGoldsmith** [comment]
I'll get it unlisted ASAP.

**Comment by austinlparker** [comment]
@MikeGoldsmith following up on this.. I still see the OpenTracing.Signed nuget package available. Any way we can get that taken down?

**Comment by MikeGoldsmith** [comment]
Hi @austinlparker - yes, I'll get it removed ASAP.

**Comment by MikeGoldsmith** [comment]
I can confirm the package is no longer available. Sorry for the (very) slow reply, I was waiting on someone else to delist it.
