### ISSUE TITLE
v0.12.0 Release Plan

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#92]
Milestone details: https://github.com/opentracing/opentracing-csharp/milestone/5

Relevant merged changes so far:
* #74 Improved XML docs
* #80 OpenTracing assembly should be signed
* #83 Updating MockTracer to use AsyncLocalScopeManager

These have been small non-breaking changes. We could do a servicing release with them but I'd prefer having fewer big releases to make sure people don't have to update their dependencies too often. For that reason, I'd like to also get some other important issues done. 

My candidates would be:
* #72 Added SetTag and WithTag for use with OpenTracing.Tag.Tags
* #75 StartActive() overload with finishSpanOnDispose:true
* #91 Use IEnumerable<KeyValuePair<string, object>> for Log() methods (again)

Would be great to get some more feedback/approval on these issues to get them done asap.

Other open questions:
* Do we already want to include an implementation for the "Trace Identifiers" RFC? If we add any of my proposed candidate issues, we will break tracers so we might as well already include this.
* Should we wait for the next Java release to have a synchronized release? There have been some commits. Not sure what else will be in their next release and when it will be.

What's your opinions on the frequency of releases? Anything else that should be included?

**Comment by MikeGoldsmith** [comment]
Hey @cwe1ss - thanks for collating the release milestone. I think what you have proposed all makes sense and I agree including the additional three commits would be beneficial.

Regarding your open questions:
- It looks like #72 and #91 are breaking changes so if Trace Identifiers RFC is signed off, I think it would be a good time to add them in 0.12 too
- I don't think we need to wait for the Java release. .NET caught up with Java in 0.11 release with a big focus on reducing inconsistencies, if they have not been able to progress on roadmap issues it shouldn't stop this project moving forward.

**Comment by cwe1ss** [comment]
I merged the other PRs and created the "0.12.0-rc1" release candidate!

Release notes: https://github.com/opentracing/opentracing-csharp/releases/tag/0.12.0-rc1
NuGet package: https://www.nuget.org/packages/OpenTracing/0.12.0-rc1

Please give it a try! I'd like to do the final release at the end of next week if there's no objections.

PS: Not sure yet if we should include #84 as well?! There's no definitive answer yet in that linked issue.

**Comment by MikeGoldsmith** [comment]
Thanks for all your work on this @cwe1ss

**Comment by cwe1ss** [comment]
No objections so far, so I'll go ahead and release it NOW.

**Comment by cwe1ss** [comment]
v0.12.0 has been released!

Release notes: https://github.com/opentracing/opentracing-csharp/releases/tag/0.12.0
NuGet package: https://www.nuget.org/packages/OpenTracing/0.12.0
