### ISSUE TITLE
Transform "OpenTracing" NuGet account to an organization

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#98]
There currently is an ["OpenTracing"](https://www.nuget.org/profiles/OpenTracing) user on NuGet.org which has access to our packages. We currently don't publish packages as this user though because we don't have the API key. That's why my NuGet account also has access to these packages.

NuGet recently [launched support for "organizations"](https://blog.nuget.org/20180417/organizations-on-nuget-org.html) which makes it much better to handle permissions & API keys. 

@bhs I think you should have the credentials for this "OpenTracing" user, right? Could you please follow [this how-to](https://docs.microsoft.com/en-us/nuget/reference/organizations-on-nuget-org#transform-existing-account-to-an-organization) to transform the account. If you set me as the new administrator (christian@chwe.at), I'll take care of the rest.

**Comment by cwe1ss** [comment]
@bhs I'm assigning this to you. Feel free to do this as you please, or assign it to someone else who has the credentials to that account.

**Comment by bhs** [comment]
@cwe1ss sorry for the delay.

![image](https://user-images.githubusercontent.com/2251553/39979353-d3d0e648-56fa-11e8-86e6-0b08b2f445f2.png)

I think you should be all good to finish the process... I had to enter your NuGet username (`cwe1ss`) rather than your email address, by the way.

**Comment by cwe1ss** [comment]
@bhs - thank you! I'm now an administrator of the organization.

@MikeGoldsmith what's your nuget username? I'll add you as well if you want (since you're also an AppVeyor admin)

**Comment by MikeGoldsmith** [comment]
@cwe1ss nuget username is `mikegoldsmith`

**Comment by MikeGoldsmith** [comment]
Accepted - thanks

**Comment by cwe1ss** [comment]
🍻

**Comment by cwe1ss** [comment]
fyi: I just removed the individual user account permissions from the NuGet packages so every release now has to happen via this newly created organization (which is set up in AppVeyor).
